# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protofiles/enter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protofiles/enter.proto',
  package='enter',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16protofiles/enter.proto\x12\x05\x65nter\"\x13\n\x05\x45nter\x12\n\n\x02id\x18\x01 \x01(\x05\x62\x06proto3')
)




_ENTER = _descriptor.Descriptor(
  name='Enter',
  full_name='enter.Enter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='enter.Enter.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['Enter'] = _ENTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Enter = _reflection.GeneratedProtocolMessageType('Enter', (_message.Message,), dict(
  DESCRIPTOR = _ENTER,
  __module__ = 'protofiles.enter_pb2'
  # @@protoc_insertion_point(class_scope:enter.Enter)
  ))
_sym_db.RegisterMessage(Enter)


# @@protoc_insertion_point(module_scope)
